### ISSUE TITLE
Editor Role

### ISSUE THREAD

**Issue by smypf** [MentallyFriendly/gbca#11]
- [x] Able to do everything that authors are able to do (#10)
- [x] Able to mark an article as published
- [x] NICE TO HAVE - Able to mark an article as disapproved with a message why.
- [x] Able to publish an article, setting the time when the article will be put live on the site.
- [x] Able to unpublish an article, removing it from the frontend of the site.

**Comment by gillcosta** [comment]
@smypf Can we please add the icon attached when an article gets rejected by the Editor

![reject](https://cloud.githubusercontent.com/assets/7959199/22229222/819c5344-e22a-11e6-9c1b-d12a5713c3e3.png)
