### ISSUE TITLE
Editor approval queue

### ISSUE THREAD

**Issue by smypf** [MentallyFriendly/gbca#14]
- [x] Able to review a list of articles that are waiting for approval, ordered by last changed date
- [x] Add link to admin menu, only visible to editors and admin
- [x] Able to mass approve articles using checkboxes

**Comment by gillcosta** [comment]
@smypf Why is this blocked?

**Comment by smypf** [comment]
Sorry, should have said. This needs to be implemented into the Pages functionality, which we're waiting on assistance from Francois. This works for articles and news.

**Comment by gillcosta** [comment]
@smypf 

- As an Editor, I'm unable to create a new page. 500 error.
- I'm unable to see the admin menu as an Editor.

**Comment by smypf** [comment]
@gillcosta These issues have been fixed as part of 3ef599b2eb6201f99170e4225820b2fb10ee55a9
