### ISSUE TITLE
Double up when editor added a change to the article already published

### ISSUE THREAD

**Issue by gillcosta** [MentallyFriendly/gbca#17]
http://gbca.destaging.com/showcase/people/title/
Mac Chrome

This issue is happening on the CMS modules and on the front-end previews

<img width="1273" alt="screen shot 2017-01-24 at 10 43 37 am" src="https://cloud.githubusercontent.com/assets/7959199/22227917/fe0942f6-e221-11e6-8aed-c00cba0313ad.png">

<img width="954" alt="screen shot 2017-01-24 at 10 44 02 am" src="https://cloud.githubusercontent.com/assets/7959199/22227921/0bda4a06-e222-11e6-872c-127934f5f29f.png">

<img width="1207" alt="screen shot 2017-01-24 at 10 51 31 am" src="https://cloud.githubusercontent.com/assets/7959199/22228121/1925b1e0-e223-11e6-8c5b-f87731ef238a.png">

**Comment by smypf** [comment]
Will check what happening.

**Comment by smypf** [comment]
I've made adjustments to ensure that the duplicated content pieces aren't happening, and to prevent the old revisions from being shown.
