### ISSUE TITLE
Author should be able to view the article created by a Editor on the CMS

### ISSUE THREAD

**Issue by gillcosta** [MentallyFriendly/gbca#18]
http://gbca.destaging.com/gbca-admin/gbca/article/60/#tab_article_main

**Comment by smypf** [comment]
Are you sure? That's not how I interpreted the functionality. Authors should only be able to edit their own content.

**Comment by gillcosta** [comment]
@smypf If the editor created the article, the author should be able to view and edit the article. Not publish.

**Comment by smypf** [comment]
Ok

The client asked for this as well so it has been done.

0049d251a48a62455bf03e1a0d6e1ff086247bed
