### ISSUE TITLE
Add "updated_at" field to listing page.

### ISSUE THREAD

**Issue by smypf** [MentallyFriendly/gbca#25]

**Comment by smypf** [comment]
I can't remember what this is about. @gillcosta any idea?

**Comment by gillcosta** [comment]
@smypf Maybe it's about showing when the article was last updated?

**Comment by smypf** [comment]
That's the one.

I remembered it over the weekend.

![screen shot 2017-01-30 at 11 26 10 am](https://cloud.githubusercontent.com/assets/133069/22409522/eba89212-e6de-11e6-900f-54261cb21d45.png)
