### ISSUE TITLE
Homepage message from the CEO automatically populated

### ISSUE THREAD

**Issue by smypf** [MentallyFriendly/gbca#5]
Automatically pulls first time, blurb and title from latest article in CEO category.

**Comment by smypf** [comment]
Please be aware that this doesn't specifically select a "CEO" news article, but rather allows the user to select a news category which will have the latest article from this category shown on the page.

**Comment by gillcosta** [comment]
@smypf I've created an article and selected the category "GBCA News - Recent". The article is now showing up on the homepage. Did I do this right?
http://gbca.destaging.com/gbca-admin/gbca/news/25/#tab_news_main

**Comment by smypf** [comment]
This has been fixed.
